"""altering table todos

Revision ID: 4908d4dedc36
Revises: 9e92740bb223
Create Date: 2018-10-16 18:40:25.331898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4908d4dedc36'
down_revision = '9e92740bb223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('description', sa.String(length=50), nullable=True))
    op.drop_column('todo', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('title', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('todo', 'description')
    # ### end Alembic commands ###
